const songs = [
  {
    id:'1',
    title: "Billie Jean",
    artist: 'Michael Jackson',
    album: "Thriller 25th Sup...",
    playingCount: '1.040.811.084',
    time: "4:53",
    duration:"4:53",
    image: '/assets/images/image1.png',
    src: "/assets/audio/track1.mp3", 
  },
  {
    id:'2',
    title: 'Beat It',
    artist: 'Michael Jackson',
    album: 'Thriller 25th Sup...',
    time: '4:58',
    playingCount: '634.786.045',
    image: '/assets/images/image1.png',
    src: '/assets/audio/track2.mp3',
  },
  {
    id:'3',
    title: "Smooth Criminal - 2012 Rema...",
    artist: 'Michael Jackson',
    album: "Thriller 25th Sup...",
    playingCount: '407.234.004',
    time: "4:17",
    image: '/assets/images/image2.png',
    src: "/assets/audio/track3.mp3", 
  },
  {
    id:'4',
    title: "Don't Stop 'Til You Get Enough",
    artist: 'Michael Jackson',
    album: "Bad 25th Anni...",
    playingCount: '316.391.952',
    time: "4:18",
    image: '/assets/images/image3.png',
    src: "/assets/audio/track4.mp3", 
  },
  {
    id:'5',
    title: "Rock With You - Single Version",
    artist: 'Michael Jackson',
    album: "Off The Wall",
    playingCount: '268.187.218',
    time: "3:22",
    image: '/assets/images/image3.png',
    src: "/assets/audio/track5.mp3", 
  },
];

export default songs;
